name: flutter_iadvize_sdk_example
description: Example app for flutter_iadvize_sdk_example
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_iadvize_sdk:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/test.jpeg
